name: dart_exercises
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  characters: ^1.3.0
  
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
